### PR TITLE
enable menu toggle, use flex grow and shrink

### PR DESCRIPTION
**Pull request by decentraliser**
- enable drawer toggle
- use flex shrink and grow for app main flex props
- make view titles uniform
- use standard v-alert for errors

I wanted to split this PR, but I messed up with git rebase... :s

Could we agree on the prettier we use so we avoid some commit noise?

### CODE REVIEW

**Comment by jontey** [comment]
Does prettier support .vue files?

**Comment by decentraliser** [comment]
I used the word "prettier" as a general term,  I don't use this module in particular

I am using VScode, and I think that the Vetur module is taking care of the formatting

Every time I format a document it is changing your display, what are you using? 
Would be much better if we have the same settings and all enable format on save option

**Comment by jontey** [comment]
> I used the word "prettier" as a general term, I don't use this module in particular

Understood. 

> Every time I format a document it is changing your display, what are you using?

I use eslint with the vue plugin since there is already an .eslint definition in the project. 

If you are using VS Code (with eslint extension installed) you can paste this file in `.vscode/settings.json` https://github.com/luxtagofficial/nem2-wallet-browserextension/blob/b86cbce23240b88119cb7173f31d66b4ac3954bc/.vscode/settings.json

**Comment by decentraliser** [comment]
done! It seems to do the trick as if I go to developermode files there are no red lines

@aleixmorgadas maybe we could push the .vscode settings.json if you will

**Comment by decentraliser** [comment]
OK now I get it about the prettier. EsLint Vue plugin does not come with a prettifier.
For having one, you need to install Vetur plugin, then you can have a prettify on alt+shit+F and autosave if you want to
BUT
you need to tweak Vetur settings like that
>  "vetur.format.defaultFormatter.js": "prettier",
>  "vetur.format.defaultFormatter.css": "prettier"

the prettyfier is still not perfect like that though, but acceptable

**Comment by aleixmorgadas** [comment]
> @aleixmorgadas maybe we could push the .vscode settings.json if you will

Better to not push `.vscode` files, I, for example, use IntelliJ. we should keep IDE agnostic

**Pull request merged**
