### PR TITLE
Namespace Component

### PR DESCRIPTION
**Pull request by planethouki**
related #2 
- rent namespace and subnamespace
- list owned namespace

### CODE REVIEW

**Comment by aleixmorgadas** [comment]
Hi @planethouki ,

I see you have a list of things to do. Should I wait to merge the Pull Request until you finish everything? I prefer to do little PR instead of big ones.

By the way, GitHub introduced a new feature to mark a Pull Request as Draft. [Check it here](https://github.blog/2019-02-14-introducing-draft-pull-requests/). Using this feature, you explicit say that it's a Work In Progress Pull Request.

**Comment by planethouki** [comment]
Hi @aleixmorgadas .
Thank you for your message. I apologize for the confusion.
You don't have to wait for the checklist to fill.
Please confirm only this pull request.

they are future pull request
- transaction send notification
- namespaceHttp with QueryParams
- ns expiration, parentId and more
- ? mosaic alias tx
- ? address alias tx

**Comment by CrackTheCode016** [comment]
> * transaction send notification

Hi @planethouki, I am actually making a dialog component to do this.  It will allow a `transaction` as an argument where it will sign + send after confirmation so you don't have to make it for now :) unless you want to of course, please let me know.

**Comment by planethouki** [comment]
Hi @CrackTheCode016 .
thanks! i'll use your dialog.

**Pull request merged**
