### PR TITLE
added to Handler, using Confirmation component

### PR DESCRIPTION
**Pull request by CrackTheCode016**
Added a bit more functionality to the Handler view, as well as updated the `nem2-uri-scheme` along the way to reflect the changes we had to make to it.  Handler is now properly using `Confirmation.vue`

Still need to add a sendconfirmation to ensure the transaction has been sent, and to alert the user.

### CODE REVIEW

**Comment by CrackTheCode016** [comment]
We have a small conflict to do with the nem2-uri package version ^^

**Comment by aleixmorgadas** [comment]
Feel free to re-write package-lock.json

**Comment by decentraliser** [comment]
you can just delete the package-lock, and commit

**Comment by aleixmorgadas** [comment]
The PR is closed, do you plan to make a new one? Or how we proceed?

**Comment by CrackTheCode016** [comment]
> The PR is closed, do you plan to make a new one? Or how we proceed?

I plan to make a new one, I'd like to change some things around anyways ^^

**Pull request closed without merging**
